spring:
  profiles:
    active: dev

#first db
datasource:
  url:  jdbc:oracle:thin:@localhost:1521/orcl
  username: NETCRACKER
  password: NETCRACKER
  driver-class-name: oracle.jdbc.OracleDriver

#second db
secondDatasource:
  url:  jdbc:oracle:thin:@localhost:1521/orcl
  username: LANDING
  password: LANDING
  driver-class-name: oracle.jdbc.OracleDriver

#  jpa:
#    database-platform: org.hibernate.dialect.Oracle10gDialect
#    generate-ddl: true

server:
  port: 8083
#  contextPath: /service

logging:
  pattern:
    file: "%d %-5level [%thread] %logger : %msg%n"

multipart:
  maxFileSize: 128KB
  maxRequestSize: 128KB