spring:
  profiles:
    active: prod

server:
  port: 8084
  contextPath: /

logging:
  pattern:
    file: "%d %-5level [%thread] %logger : %msg%n"

multipart:
  maxFileSize: 128KB
  maxRequestSize: 128KB